#pragma once

#ifdef __cplusplus
namespace db
{
extern "C" {
#endif

#define SENSOR_PARAM_COUNT 50

enum EepromAdress {
  PRIMARY_SENSOR_STATUS_MEAN_VALUE = 1,
  PRIMARY_SENSOR_MEAN_VALUE,
  PRIMARY_SENSOR_DEVIATION,
  PRIMARY_SENSOR_BLUE_DIAMETER,
  PRIMARY_SENSOR_MAGENTA_DIAMETER,
  PRIMARY_SENSOR_OVALITY,
  PRIMARY_SENSOR_POSITION_AXIS_BLUE,
  PRIMARY_SENSOR_POSITION_AXIS_MAGENTA,
  SECONDARY_SENSOR_STATUS_MEAN_VALUE = SENSOR_PARAM_COUNT,
  SECONDARY_SENSOR_MEAN_VALUE,
  SECONDARY_SENSOR_DEVIATION,
  SECONDARY_SENSOR_BLUE_DIAMETER,
  SECONDARY_SENSOR_MAGENTA_DIAMETER,
  SECONDARY_SENSOR_OVALITY,
  SECONDARY_SENSOR_POSITION_AXIS_BLUE,
  SECONDARY_SENSOR_POSITION_AXIS_MAGENTA,
  PRIMARY_PORT_BAUDRATE = SENSOR_PARAM_COUNT * 2,
  SECONDARY_PORT_BAUDRATE,
  PRIMARY_PORT_PROTOCOL,
  PC_PORT_BAUDRATE,
  SECONDARY_PORT_PROTOCOL,
  NO_EEPROM_LOC
};

#ifdef __cplusplus
} // extern "C"
} // namespace db

#endif